apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2022-12-15T05:36:20.851055627Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.4
    description: Deploy components and dependencies of azure-service-operator
    digest: 6c66c0316d57e0f8a4251d8110fe77626ef13d5b124dd1e0d9c5f7788f4a36b8
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v2
    created: "2022-12-15T05:36:20.813090726Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.3
    description: Deploy components and dependencies of azure-service-operator
    digest: 51ae0842a96c86f3999455d5b4ca7a81b1e39b5b9c78ad078d82e628699b7bbe
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v2
    created: "2022-12-15T05:36:20.779249505Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.2
    description: Deploy components and dependencies of azure-service-operator
    digest: 13b4b6f943860ef241ff735cd2717af0b4b98454cd6f95315006e2ae60060a79
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v2
    created: "2022-12-15T05:36:20.749843959Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-beta.1
    description: Deploy components and dependencies of azure-service-operator
    digest: 70275156e4dea3fba2847481930bb255e051090edd4d11d57812534be70b099b
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2022-12-15T05:36:20.714741044Z"
    dependencies:
    - condition: installCRDs
      name: azure-service-operator-crds
      repository: ""
      version: v2.0.0-alpha.6
    description: Deploy components and dependencies of azure-service-operator
    digest: 46d98178fcc807204382b156bf1310b101e0ac9defefc3654e11b976e11a550a
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.0.tgz
    version: v2.0.0-beta.0
  - apiVersion: v2
    created: "2022-12-15T05:36:20.691795165Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 644b1f9e38f7cd868963e52dc449cbb16231c10b3ee0ba303e864f1a392444fb
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-alpha.6.tgz
    version: v2.0.0-alpha.6
  azure-service-operator-crds:
  - apiVersion: v2
    created: "2022-12-15T05:36:20.67748644Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 420e582558d1691298cae15e57c81ebd68b84b8c27287e328b3f1ab372ecbde4
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v2
    created: "2022-12-15T05:36:20.64530121Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 5feb153b1020a3636914db3e98e316b8cb29f2d7df7bba7282124e186ee323c2
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v2
    created: "2022-12-15T05:36:20.615116569Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 8f38f08e53bae760fdf34129af116e1587396e061a1c97c54845c6fe42b1e349
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v2
    created: "2022-12-15T05:36:20.581481746Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: afc2b2b4d46b92ec0f0a23aee7864fa6e7fea59c4aed3cc91528e57da5fb9374
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2022-12-15T05:36:20.557150874Z"
    description: Install Custom Resources for Azure Service Operator v2
    digest: 7578c1a1f32301d906ad5b09abd627b0e82ea4dde2b51d7fdf04bc21fe1e8643
    name: azure-service-operator-crds
    urls:
    - azure-service-operator-crds-v2.0.0-beta.0.tgz
    version: v2.0.0-beta.0
generated: "2022-12-15T05:36:20.531805407Z"
